name: pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  run-tests:
    name: Run script on test repo and check output with pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
    - name: Download test repo
      run: ./scripts/init-for-tests
    - name: Run GPTH on test repo
      run: |
        python google_photos_takeout_helper/__main__.py \
          -i "../__takeout_helper_test_data__/Google Photos" \
          -o "../__takeout_helper_test_data__/output"
    - name: Run pytest
      run: pytest
